### ISSUE TITLE
Remove flask restful

### ISSUE THREAD

**Issue by Adrian-St** [hpi-sam/ask-your-repository-api#27]
Options to accomplish this:

- Use plain flask pluggable views: http://flask.pocoo.org/docs/1.0/views/ : 
  - Very few additional features
  - Requires writing our own helpers/decorators for response parsing
  - Requires writing our own helpers/decorators for request parsing
  - Requires writing our own helpers for routing
  - We can probably reuse a lot of our existing code here
  - Very flexible

- Use Flask Apispec https://pypi.org/project/flask-apispec/:
  - Offers a auto generated swagger UI
  - Offers helpers for request parsing (`@use_kwargs`)
  - Offers helpers for response parsing(`@marshall_with`)
  - Uses our current library stack with a few helper methods
  - flexible
  
- Using Flask-Restplus https://flask-restplus.readthedocs.io/en/stable/index.html:
  - Offers a auto-generated swagger UI
  - Offers helpers for request parsing (but are deprecated for marshmallow)
  - Offers helpers for response parsing(`@marshall_with`) but uses custom model definitions (not marshmallow)
  - Very fully fleshed out framework so not as flexible

Todo:
  - Decide which solution to use (personally pref flask-apispec)
  - Refactor all routes to use the new schema
  - Delete Flask-Restful from dependencies and all associated helpers (most of python on segways)
______
We don't really use the features of flask restful anymore.
Might be feasable to remove flask restful entirely.

**Comment by Askir** [comment]
Please specify what is "not really". What do we want to replace it with and how routing should be done in general. Flask-ApiSpec has something to do with this as well.

**Comment by Adrian-St** [comment]
Another options would be flask-rest-plus: https://flask-restplus.readthedocs.io/en/stable/

**Comment by Askir** [comment]
Okay so our options on refactoring our routing are:

- Use plain flask pluggable views: http://flask.pocoo.org/docs/1.0/views/ : 
  - Very few additional features
  - Requires writing our own helpers/decorators for response parsing
  - Requires writing our own helpers/decorators for request parsing
  - Requires writing our own helpers for routing
  - We can probably reuse a lot of our existing code here
  - Very flexible

- Use Flask Apispec https://pypi.org/project/flask-apispec/:
  - Offers a auto generated swagger UI
  - Offers helpers for request parsing (`@use_kwargs`)
  - Offers helpers for response parsing(`@marshall_with`)
  - Uses our current library stack with a few helper methods
  - flexible
  
- Using Flask-Restplus https://flask-restplus.readthedocs.io/en/stable/index.html:
  - Offers a auto-generated swagger UI
  - Offers helpers for request parsing (but are deprecated for marshmallow)
  - Offers helpers for response parsing(`@marshall_with`) but uses custom model definitions (not marshmallow)
  - Very fully fleshed out framework so not as flexible

Todo:
  - Decide which solution to use (personally pref flask-apispec)
  - Refactor all routes to use the new schema
  - Delete Flask-Restful from dependencies and all associated helpers (most of python on segways)
